Support Custom Protocol
sindresorhus/normalize-url pull request #153
Opened 2021-09-01 06:04 UTC by brandon93s

I may be oversimplifying here, but this feels like a bug fix to not apply the protocol prefix when a custom prefix is present.  Retains existing functionality and adds support for custom protocols.

2021-09-07 09:59 UTC, sindresorhus requested changes

2021-09-07 09:59 UTC, sindresorhus commented on test.js
> +	t.is(normalizeUrl('custom://sindresorhus.com'), 'custom://sindresorhus.com');
Can you also add a test with `custom:sindresorhus.com` (no slashes)?

2021-09-07 09:59 UTC, sindresorhus commented on index.js
> +	if (!isRelativeUrl & !hasCustomProtocol) {
```suggestion
	if (!isRelativeUrl && !hasCustomProtocol) {
```

2021-09-07 10:00 UTC, sindresorhus commented
From the issue:

> See #132 and the feedback given there.

Did you?

2021-09-24 22:04 UTC, dink42 approved these changes

2022-01-06 12:13 UTC, sindresorhus commented
Friendly bump :)

2022-03-14 02:34 UTC, jsmarketingrus approved these changes

2022-03-14 12:36 UTC, dink42 approved these changes

2022-03-14 12:36 UTC, dink42 approved these changes
Approve

2022-09-01 13:34 UTC, sindresorhus commented on index.js
> +	const hasCustomProtocol = /^[a-z.+-]*[.+-][a-z.+-]*:\/\//i.test(urlString);
```suggestion
	const hasCustomProtocol = /^[a-z][a-z.+-]*?[.+-][a-z.+-]*?:/i.test(urlString);
```

a protocol does not need `//` and it has to start with `a-z`: https://stackoverflow.com/questions/3641722/valid-characters-for-uri-schemes

2022-09-01 13:34 UTC, sindresorhus commented on index.js
> +	const hasCustomProtocol = /^[a-z.+-]*[.+-][a-z.+-]*:\/\//i.test(urlString);
Also add a sensible length limit to prevent ReDoS abuse.

2022-09-19 02:23 UTC, Vladisvob approved these changes

2022-09-19 02:25 UTC, Vladisvob approved these changes

2022-09-19 02:28 UTC, Vladisvob approved these changes

2022-11-04 07:55 UTC, closed without merging