Add removeQueryParametersByValue option
sindresorhus/normalize-url pull request #176
Opened 2022-10-17 17:10 UTC by mlshvdv

The option `removeQueryParametersByValue` removes query parameters that match the specified values. May be helpful to make a canonical URL.

```js
normalizeUrl('www.sindresorhus.com?foo=bar&page=1&page_size=30', {
	removeQueryParametersByValue: [
		{
			key: 'page',
			value: 1
		},
		{
			key: 'page_size',
			value: 10
		}
	]
});
//=> 'http://sindresorhus.com/?foo=bar&page_size=30'
```

2022-10-17 17:20 UTC, sindresorhus commented
Do you have an actual real-world use-case for this?

2022-10-17 17:24 UTC, sindresorhus requested changes

2022-10-17 17:24 UTC, sindresorhus commented on index.d.ts
> +	readonly removeQueryParametersByValue?: ReadonlyArray<{key: string; value: string | number}> | undefined;
`ByValue` is not correct as it's "by key & value".

2022-10-17 17:24 UTC, sindresorhus commented on index.d.ts
> +	readonly removeQueryParametersByValue?: ReadonlyArray<{key: string; value: string | number}> | undefined;
I would prefer to just include it in the `removeQueryParameters` option.

2022-10-17 17:24 UTC, sindresorhus commented on index.d.ts
> +@param options — options
This is not needed.

2022-10-17 17:24 UTC, sindresorhus commented on index.d.ts
> +				value: 10
I realize this is to show it wouldn't apply the given URL, but removing a `page_size` of `10` makes no sense and will just confuse the user.

2022-10-17 17:24 UTC, sindresorhus commented on test.js
> +	t.is(normalizeUrl('www.sindresorhus.com?foo=bar&page=2&page_size=20', options), 'http://www.sindresorhus.com/?foo=bar&page=2&page_size=20');
```suggestion
	t.is(normalizeUrl('https://sindresorhus.com/?page=1&page_size=10', options), 'https://sindresorhus.com');
	t.is(normalizeUrl('https://sindresorhus.com?foo=bar&page=2&page_size=10', options), 'https://sindresorhus.com/?foo=bar&page=2');
	t.is(normalizeUrl('https://sindresorhus.com?foo=bar&page=2&page_size=20', options), 'https://sindresorhus.com/?foo=bar&page=2&page_size=20');
```

2022-10-17 17:31 UTC, mlshvdv commented
@sindresorhus 

For example, the pages `https://example.com/posts` and `https://example.com/posts?page=1` are the same. When you need to create a canonical URL for a search engine's crawler (to put in `<link rel="canonical" href="https://..." />`, the option `removeQueryParametersByValue` will help with it to prevent page duplication (https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls)

Another example. The page has a posts list where users can choose post count per page. By default, only 10 records are displayed per page. In that case, we don't need to have `page_size=10` in the URL for pagination. But, when the user chooses another number, for example `25`, the full canonical URL for this page must contain `page_size=25`.

2022-10-27 11:09 UTC, sindresorhus commented
Alright. Makes sense. I think you should document the use-case in text though. That it's useful when you want to remove query parameters that are the same as the default.

2024-02-28 08:06 UTC, closed without merging